In [1]:
%matplotlib qt

In [2]:
import matplotlib as mpl
import happi
import numpy as np
import matplotlib.pyplot as plt

jetcmap = plt.cm.get_cmap("jet", 9) #generate a jet map with 10 values "rainbow", "jet", YlOrRd
jet_vals = jetcmap(np.arange(9)) #extract those values as an array 
jet_vals[0] = [1.0, 1, 1.0, 1] #change the first value 
jet_vals[8] = [0.0, 0, 0.0, 1] #change the first value 
newcmap = mpl.colors.LinearSegmentedColormap.from_list("mine", jet_vals) 

/var/folders/2t/97rc3fl92tg15k2l_4sk5hsh0000gn/T/ipykernel_47739/616493249.py:6: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap(obj)`` instead.
  jetcmap = plt.cm.get_cmap("jet", 9) #generate a jet map with 10 values "rainbow", "jet", YlOrRd
2024-05-05 09:03:09.548 Python[47739:927837] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.


In [3]:
# plt.rc('font', family='sans-serif', serif='Arial')
# plt.rc('text', usetex=False)
# plt.rc('xtick', labelsize=12)
# plt.rc('ytick', labelsize=12)
# plt.rc('axes', labelsize=12)
# plt.rc('legend', fontsize=12)

# plt.rc('font', family='sans-serif', serif='Arial')

from matplotlib import font_manager

font_dirs = ['/Users/yao/Documents/Calibri and Cambria Fonts/']
font_files = font_manager.findSystemFonts(fontpaths=font_dirs)

for font_file in font_files:
    font_manager.fontManager.addfont(font_file)

# set font
plt.rcParams['font.family'] = 'Calibri'

plt.rc('text', usetex=False)
plt.rc('xtick', labelsize=10)
plt.rc('ytick', labelsize=10)
plt.rc('axes', labelsize=10)
plt.rc('legend', fontsize=9)

width  = 3.487
height = width / 1.618 * 1.0

In [20]:
wkdir = [
    '/Users/yao/Desktop/test/',
    '/Users/yao/Desktop/test1/',
    ]

In [103]:
S0 = happi.Open(wkdir[0], reference_angular_frequency_SI = 2.*np.pi*3e8/1.058e-6)
S1 = happi.Open(wkdir[1], reference_angular_frequency_SI = 2.*np.pi*3e8/1.058e-6)

Loaded simulation '/Users/yao/Desktop/test/'
Scanning for Scalar diagnostics
Scanning for Field diagnostics
Scanning for Probe diagnostics
Scanning for ParticleBinning diagnostics
Scanning for RadiationSpectrum diagnostics
Scanning for Performance diagnostics
Scanning for Screen diagnostics
Scanning for Tracked particle diagnostics
Scanning for new particle diagnostics
Loaded simulation '/Users/yao/Desktop/test1/'
Scanning for Scalar diagnostics
Scanning for Field diagnostics
Scanning for Probe diagnostics
Scanning for ParticleBinning diagnostics
Scanning for RadiationSpectrum diagnostics
Scanning for Performance diagnostics
Scanning for Screen diagnostics
Scanning for Tracked particle diagnostics
Scanning for new particle diagnostics


In [22]:
# prepare constants, units

me = 9.1e-31
mp = 1836.*me
qe = 1.6e-19
ep = 8.9e-12  # epsilon_0
c  = 3.0e8
wr = 2.*np.pi*3e8/1.058e-6
de = c / wr
# Lx = S0.namelist.L_x.real * de * 1e3      # in mm
# dx = S0.namelist.d_x * de * 1e3           # in mm

Te = S0.namelist.temp_e * 511.e3             # in eV
ne = S0.namelist.n0 * 1.1e21                 # in cm-3
ld = 7.43e2 * Te**0.5 * ne**(-0.5) * 10. # in mm
# dt = S0.namelist.d_t

# B0 = S0.namelist.B_z * (me * wr / qe)
# wc = qe * B0 / me


In [124]:
S1.RadiationSpectrum(0,units=['fs','um'],
                     data_log=True,
                     cmap=newcmap,
                    vmin=-7,
                    vmax=-4,
                    ).slide()


#0 -  of species # 0
    user_function0 from -90 to 90 in 200 steps 
    gamma from 1e-07 to 195.695 in 100 steps  [ LOG SCALE ]  [ INCLUDING EDGES ] 

The value in each bin is the sum of the `deposited_quantity` divided by the bin size and by grid_length[0] * grid_length[1]



/Users/yao/Smilei/happi/_Diagnostics/Diagnostic.py:857: RuntimeWarning: divide by zero encountered in log10
  return self._np.log10( self._dataLinAtTime(t) )


In [30]:
dpm = S1.RadiationSpectrum(0, units=['fs','um'],
                           data_log=True,
                           cmap=newcmap,
                           vmin=-7,
                           vmax=-4,
                          )

ndp = S0.RadiationSpectrum(0, units=['fs','um'],
                           data_log=True,
                           cmap=newcmap,
                           vmin=-7,
                           vmax=-4,
                          )

happi.multiSlide(dpm,ndp,shape=[2,1])

In [107]:
S1.RadiationSpectrum(0,units=['fs','um'],
                     data_log=True,
                     cmap=newcmap,
                    vmin=-7,
                    vmax=-4,
                    ).slide()


#0 -  of species # 0
    user_function0 from -90 to 90 in 200 steps 
    gamma from 1e-07 to 195.695 in 100 steps  [ LOG SCALE ]  [ INCLUDING EDGES ] 

The value in each bin is the sum of the `deposited_quantity` divided by the bin size and by grid_length[0] * grid_length[1]



In [8]:
aa = np.array( S0.RadiationSpectrum(0).getData() )

In [9]:
aa.max()

5.4713481406869605e-05

In [100]:
time0 = np.array(S0.RadiationSpectrum(0,
                   # data_log=True,
                   units=['um','fs','keV cm^-3'
                         ],
                   # sum={'ekin':[0.8,2]},
                   # cmap='inferno_r',
                   # vmin=22,
                   # vmax=27,
                        ).getTimes())

time2 = np.array(S1.RadiationSpectrum(0,
                   # data_log=True,
                   units=['um','fs','keV cm^-3'
                         ],
                   # sum={'ekin':[0.8,2]},
                   # cmap='inferno_r',
                   # vmin=22,
                   # vmax=27,
                        ).getTimes())

In [108]:
ed0 = np.array(S0.RadiationSpectrum(0,
                   # data_log=True,
                   units=['um','fs','keV cm^-3'
                         ],
                   sum={'photon_energy_axis':'all'},
                   cmap='inferno_r',
                   # vmin=-7,
                   # vmax=-4,
                        ).getData())
                  # ).animate(movie='/Users/yao/Desktop/ene_dens_ndpm.gif')
                  # ).slide()

ed2 = np.array(S1.RadiationSpectrum(0,
                   # data_log=True,
                   units=['um','fs','keV cm^-3'
                         ],
                   sum={'photon_energy_axis':'all'},
                   cmap='inferno_r',
                   # vmin=-7,
                   # vmax=-4,
                        ).getData())

In [81]:
ed0_sum = np.sum(ed0,axis=2)
ed2_sum = np.sum(ed2,axis=2)

In [82]:
angles = np.array(S1.RadiationSpectrum(0).getAxis('user_function0'))

In [83]:
ed0_sum

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.11776924e-04, 1.12850999e-04, 1.13329167e-04, ...,
        1.10264859e-04, 1.14226634e-04, 1.12298299e-04],
       [7.56291796e-05, 7.61194672e-05, 7.68928808e-05, ...,
        7.84044398e-05, 7.84066320e-05, 7.75608790e-05],
       ...,
       [4.52280909e-04, 4.43310043e-04, 4.52729474e-04, ...,
        4.72418469e-04, 4.58194832e-04, 4.63732588e-04],
       [4.13776366e-04, 4.17010368e-04, 4.16855071e-04, ...,
        4.35554003e-04, 4.32594150e-04, 4.37682583e-04],
       [3.81991100e-04, 3.89129443e-04, 3.84209459e-04, ...,
        3.98586020e-04, 4.04476139e-04, 3.96795550e-04]])

In [85]:
width  = 3.487 * 1.3
height = width / 1.618 * 1.2

fig, ax = plt.subplots()
fig.subplots_adjust(left=.15, bottom=.16, right=.99, top=.97)

ax.plot(angles,ed0_sum[id0], color='b',lw=1.0,
             linestyle='-',
             label='Sim. no DPM',
           )

ax.plot(angles,ed2_sum[id2], color='r',lw=1.0,
             linestyle='--',
             label='Sim. w/ DPM',
           )


ax.set_xlim([-90,90])
# ax.set_ylim([1e-5,1e0])
# ax.set_yticks([1, 1e-2, 1e-4])
# plt.title('time = '+str(tt[ts])+' fs')
# ax.grid(which='both',linestyle='--',alpha=0.5)
ax.set_xlabel(r'Angles ($\degree$)')
# ax.set_ylabel('Normalized dN/dE')

ax.legend(fancybox=False, frameon=False)
fig.set_size_inches(width, height)
fig.tight_layout()

In [87]:
from mpl_toolkits.axes_grid1 import make_axes_locatable
from mpl_toolkits.axes_grid1 import ImageGrid

id0 = 30
id2 = 28

width  = 3.487 * 2.0
height = width / 1.618 * 1.0

fig = plt.figure(figsize=(width, height))

# fig, ax = plt.subplots()
# fig.subplots_adjust(left=.15, bottom=.16, right=.99, top=.97)

grid = ImageGrid(fig, 111,          # as in plt.subplot(111)
                 nrows_ncols=(1,2),
                 axes_pad=0.35,
                 share_all=True,
                 cbar_location="right",
                 cbar_mode="single",
                 cbar_size="5%",
                 cbar_pad=0.1,
                 )

im0 = grid[0].imshow((np.log10(ed2[id2].T)),
           cmap='inferno_r',
           origin='lower',
           extent=[-90,90,-7,2],
           vmin=-7,
           vmax=-4,
           aspect=10,
          )

im1 = grid[1].imshow((np.log10(ed0[id0].T)),
           cmap='inferno_r',
           origin='lower',
           extent=[-90,90,-7,2],
           vmin=-7,
           vmax=-4,
           aspect=10,
          )

# grid[0].set_xlim(1,21)
# grid[1].set_xlim(1,21)
# grid[1].set_ylim(7,35)
# grid[0].set_ylim(7,35)
# grid[0].set_xlabel(r'x ($\mu$m)')
# grid[1].set_xlabel(r'x ($\mu$m)')
# grid[0].set_ylabel(r'y ($\mu$m)')
# # grid[0].set_xticks([0, 7, 14,  21])
# grid[1].set_xticks([1, 6, 11, 16, 21])
# # grid[0].set_yticks([0, 7, 14, 21, 28, 35, 42])
# grid[0].set_yticks([7, 14, 21, 28, 35])
grid[1].set_title('time = {:.1f} fs'.format(time0[id0]))
grid[0].set_title('time = {:.1f} fs'.format(time2[id2]))
grid[0].grid(linestyle='--',color='grey',alpha=0.5)
grid[1].grid(linestyle='--',color='grey',alpha=0.5)

# Colorbar
grid[1].cax.colorbar(im1)
grid[1].cax.cla()
mpl.colorbar.Colorbar(grid[1].cax,im1)
cax = grid.cbar_axes[0]
axis = cax.axis[cax.orientation]
# axis.label.set_text(r'$n_e$ $\varepsilon_{kin}$ (cm$^{-3}$ $\cdot$ keV)')
# grid[1].cax.toggle_label(r'$n_p (cm^{-3})$')
# grid[1].cax.tick_params(size=0)
# grid[1].cax.toggle_label(True)
fig.tight_layout()
fig.set_size_inches(width, height)
plt.show()

/var/folders/2t/97rc3fl92tg15k2l_4sk5hsh0000gn/T/ipykernel_47739/4289739412.py:25: RuntimeWarning: divide by zero encountered in log10
  im0 = grid[0].imshow((np.log10(ed2[id2].T)),
/var/folders/2t/97rc3fl92tg15k2l_4sk5hsh0000gn/T/ipykernel_47739/4289739412.py:34: RuntimeWarning: divide by zero encountered in log10
  im1 = grid[1].imshow((np.log10(ed0[id0].T)),
/var/folders/2t/97rc3fl92tg15k2l_4sk5hsh0000gn/T/ipykernel_47739/4289739412.py:69: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  fig.tight_layout()


In [101]:
time0

array([  0.        ,  19.46554688,  38.93109375,  58.39664063,
        77.8621875 ,  97.32773438, 116.79328125, 136.25882813,
       155.724375  , 175.18992188, 194.65546875, 214.12101563,
       233.5865625 , 253.05210938, 272.51765625, 291.98320312,
       311.44875   , 330.91429687, 350.37984375, 369.84539062,
       389.3109375 , 408.77648437, 428.24203125, 447.70757812,
       467.173125  , 486.63867188, 506.10421875, 525.56976563,
       545.0353125 , 564.50085938, 583.96640625, 603.43195313,
       622.8975    , 642.36304688, 661.82859375, 681.29414063,
       700.7596875 , 720.22523438, 739.69078125, 759.15632813,
       778.621875  ])

In [102]:
time2

array([  0.        ,   3.23736979,   6.47473958,   9.71210938,
        12.94947917,  16.18684896,  19.42421875,  22.66158854,
        25.89895833,  29.13632813,  32.37369792,  35.61106771,
        38.8484375 ,  42.08580729,  45.32317708,  48.56054688,
        51.79791667,  55.03528646,  58.27265625,  61.51002604,
        64.74739583,  67.98476563,  71.22213542,  74.45950521,
        77.696875  ,  80.93424479,  84.17161458,  87.40898438,
        90.64635417,  93.88372396,  97.12109375, 100.35846354,
       103.59583333, 106.83320313, 110.07057292, 113.30794271,
       116.5453125 , 119.78268229, 123.02005208, 126.25742188,
       129.49479167, 132.73216146, 135.96953125, 139.20690104,
       142.44427083, 145.68164062, 148.91901042, 152.15638021,
       155.39375   , 158.63111979, 161.86848958, 165.10585937,
       168.34322917, 171.58059896, 174.81796875, 178.05533854,
       181.29270833, 184.53007813, 187.76744792, 191.00481771,
       194.2421875 , 197.47955729, 200.71692708, 203.95

In [67]:
time0[0:14:1]

array([  0.        ,  19.46554688,  38.93109375,  58.39664063,
        77.8621875 ,  97.32773438, 116.79328125, 136.25882813,
       155.724375  , 175.18992188, 194.65546875, 214.12101563,
       233.5865625 , 253.05210938])

In [66]:
time2[0:84:6]

array([  0.        ,  19.42421875,  38.8484375 ,  58.27265625,
        77.696875  ,  97.12109375, 116.5453125 , 135.96953125,
       155.39375   , 174.81796875, 194.2421875 , 213.66640625,
       233.090625  , 252.51484375])

In [98]:
t0 = S0.RadiationSpectrum(0, units=['fs']).getTimes()
t0

array([  0.        ,  19.46554688,  38.93109375,  58.39664063,
        77.8621875 ,  97.32773438, 116.79328125, 136.25882813,
       155.724375  , 175.18992188, 194.65546875, 214.12101563,
       233.5865625 , 253.05210938, 272.51765625, 291.98320312,
       311.44875   , 330.91429687, 350.37984375, 369.84539062,
       389.3109375 , 408.77648437, 428.24203125, 447.70757812,
       467.173125  , 486.63867188, 506.10421875, 525.56976563,
       545.0353125 , 564.50085938, 583.96640625, 603.43195313,
       622.8975    , 642.36304688, 661.82859375, 681.29414063,
       700.7596875 , 720.22523438, 739.69078125, 759.15632813,
       778.621875  ])

In [99]:
t1 = S1.RadiationSpectrum(0, units=['fs']).getTimes()
t1.size

86

In [ ]:
S0.

In [68]:
ed0_sum.shape

(41, 200)

In [69]:
ed2_sum.shape

(86, 200)

In [116]:
ed0_sumt = np.zeros(200)
ed2_sumt = np.zeros(200)

for t in range(41):
    ed0_sumt = ed0_sumt + ed0_sum[t,:]

for t in range(41):
    t = t + 2
    ed2_sumt = ed2_sumt + ed2_sum[t*2,:]

In [122]:
width  = 3.487 * 1.3
height = width / 1.618 * 1.2

fig, ax = plt.subplots()
fig.subplots_adjust(left=.15, bottom=.16, right=.99, top=.97)

ax.plot(angles,ed0_sumt/ed0_sumt.max(), color='b',lw=1.0,
             linestyle='-',
             label='w/o. DPM',
           )

ax.plot(angles,ed2_sumt/ed0_sumt.max(), color='r',lw=1.0,
             linestyle='--',
             label='with DPM',
           )


ax.set_xlim([-90,90])
ax.set_ylim([0,1])
ax.set_xticks([-90, -60, -30, 0, 30, 60, 90])
# plt.title('time = '+str(tt[ts])+' fs')
ax.grid(which='both',linestyle='--',alpha=0.5)
ax.set_xlabel(r'Angles ($\degree$)')
ax.set_ylabel('Normalized time-integrated Radiation')

ax.legend(fancybox=False, frameon=False)
fig.set_size_inches(width, height)
fig.tight_layout()

In [123]:
fig.savefig('/Users/yao/Desktop/rad.pdf',dpi=600)

In [104]:
S0.ParticleBinning(0,units=['fs','um','V/m']).slide()


#0 - Number density of species # 0,1
    user_function0 from -90 to 90 in 200 steps 
    ekin from 0 to 195.695 in 100 steps 

The value in each bin is the sum of the `deposited_quantity` divided by the bin size and by grid_length[0] * grid_length[1]

