In [1]:
%matplotlib qt

In [2]:
import matplotlib as mpl
import happi
import numpy as np
import matplotlib.pyplot as plt

jetcmap = plt.cm.get_cmap("jet", 9) #generate a jet map with 10 values "rainbow", "jet", YlOrRd
jet_vals = jetcmap(np.arange(9)) #extract those values as an array 
jet_vals[0] = [1.0, 1, 1.0, 1] #change the first value 
jet_vals[8] = [0.0, 0, 0.0, 1] #change the first value 
newcmap = mpl.colors.LinearSegmentedColormap.from_list("mine", jet_vals) 

/var/folders/2t/97rc3fl92tg15k2l_4sk5hsh0000gn/T/ipykernel_61565/616493249.py:6: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap(obj)`` instead.
  jetcmap = plt.cm.get_cmap("jet", 9) #generate a jet map with 10 values "rainbow", "jet", YlOrRd


In [35]:
plt.rc('font', family='sans-serif', serif='Arial')
plt.rc('text', usetex=False)
plt.rc('xtick', labelsize=13)
plt.rc('ytick', labelsize=13)
plt.rc('axes', labelsize=13)
plt.rc('legend', fontsize=12)

In [4]:
import pandas as pd

In [5]:
data = pd.read_excel('/Users/yao/Nextcloud/PROJECTS/Apollon/F2-2021/figs/VH_ave.xlsx')

In [6]:
ave = np.array(pd.DataFrame(data, columns=["ave"]))
ms1 = np.array(pd.DataFrame(data, columns=["measure 1"]))
ms2 = np.array(pd.DataFrame(data, columns=["measure 2"]))
ms3 = np.array(pd.DataFrame(data, columns=["measure 3"]))
str = np.array(pd.DataFrame(data, columns=["str_mat"]))


In [21]:
# read the theoretical deposited energy in each RCF layer

import scipy.io
in_layer = scipy.io.loadmat('/Users/yao/Nextcloud/PROJECTS/Apollon/F2-2021/figs/inlayer.mat')
# in_layer = scipy.io.loadmat('/Users/yao/Desktop/in_layer_F1.mat')
inlayer = np.array(in_layer['in_layer'])


In [10]:
# use the data of F1 to check the absolute value of the spectrum

in_layer = scipy.io.loadmat('/Users/yao/Nextcloud/PROJECTS/Apollon/F2-2021/figs/in_layer_F1.mat')
inlayer = np.array(in_layer['in_layer'])

sommeOD = scipy.io.loadmat('/Users/yao/Nextcloud/PROJECTS/Apollon/F2-2021/figs/dose_F1.mat')
dose = np.array(sommeOD['sommeOD'])

In [22]:
inlayer.shape

(450, 20)

In [23]:
width  = 3.487 * 1.5
height = width / 1.618 

fig, ax = plt.subplots()
fig.subplots_adjust(left=.15, bottom=.16, right=.99, top=.97)

# experiment

ax.plot(np.linspace(1,12,12), dose[0], label='Exp')


e_inc = np.linspace(1,60,800)
spectre = np.zeros_like(e_inc)
for p in range (e_inc.size):
    spectre[p] = 800*np.exp(-1.*np.sqrt(2*e_inc[p]/2))

couche      = np.zeros_like(np.linspace(1,12,12))
for f in range(12):
    couche[f]      = np.trapz(inlayer[:,f]*spectre[:])
    
ax.plot(np.linspace(1,12,12), couche, '-r', label='Sim.')

# # ax.set_yscale('log')

ax.set_xlim([0,13])
ax.set_xticks([0,2,4,6,8,10,12,14])
ax.set_ylim([0,1000])
ax.grid(linestyle='--',alpha=0.5)
ax.set_xlabel('No. of RCF')
ax.set_ylabel('Dose (Gy)')
ax.legend(fancybox=False, reverse=True, frameon=False)
fig.set_size_inches(width, height)
fig.tight_layout()

# fig.savefig('/Users/yao/Desktop/Spec1.pdf',dpi=600)

fig, ax = plt.subplots()
fig.subplots_adjust(left=.15, bottom=.16, right=.99, top=.97)

ax.plot(e_inc, spectre*factor, '-r', label='Spectrum')
ax.set_yscale('log')

ax.set_xlim([0,60])
# ax.set_ylim([1e-1,1e3])
ax.grid(linestyle='--',alpha=0.5)
ax.set_xlabel('Energy (MeV)')
ax.set_ylabel(r'dN/dE/d$\Omega$')
ax.legend(fancybox=False, reverse=True, frameon=False)
fig.set_size_inches(width, height)
fig.tight_layout()
# fig.savefig('/Users/yao/Desktop/Spec2.pdf',dpi=600)



plt.show()

ValueError: operands could not be broadcast together with shapes (450,) (800,) 

In [14]:
factor = 2.0e10 / 32

In [24]:
inlayer.shape

(450, 20)

In [25]:
np.trapz(inlayer[:,1])

43.42103468995119

In [26]:
yerr0=[np.abs(np.minimum(ave[:,0]-ms1[:,0], ave[:,0]-ms2[:,0], ave[:,0]-ms3[:,0]))/ave[0,0],
       np.maximum(ave[:,0]-ms1[:,0], ave[:,0]-ms2[:,0], ave[:,0]-ms3[:,0])/ave[0,0]
      ]

In [27]:
width  = 3.487 * 1.5
height = width / 1.618 

fig, ax = plt.subplots()
fig.subplots_adjust(left=.15, bottom=.16, right=.99, top=.97)

# experiment
ax.errorbar(np.linspace(1,14,14),
            ave[:,0]/ave[11,0],
            yerr=yerr0, 
            fmt='-k',markersize=8,
            mfc='none',
            ecolor='k',elinewidth=2.0,
            capsize=2.0, capthick = 2.0,
            label='Exp.'
           )


e_inc = np.linspace(1,45,450)
spectre = np.zeros_like(e_inc)
spectre_low  = np.zeros_like(e_inc)
spectre_high1 = np.zeros_like(e_inc)
spectre_high2 = np.zeros_like(e_inc)
for p in range (e_inc.size):
    spectre_low[p] = 20*np.exp(-1.*np.sqrt(2*e_inc[p]/0.5))
    # if e_inc[p] > 20:
    spectre_high1[p] = 0.1*np.exp(-0.5*((e_inc[p]-27.)/3.5)**4)
    # else:
    spectre_high2[p] = 0.03*np.exp(-0.5*((e_inc[p]-22.)/5)**4)
    spectre[p] =  spectre_low[p] + spectre_high1[p] + spectre_high2[p]

couche_low  = np.zeros_like(np.linspace(1,14,14))
couche_high1 = np.zeros_like(np.linspace(1,14,14))
couche_high2 = np.zeros_like(np.linspace(1,14,14))
couche      = np.zeros_like(np.linspace(1,14,14))
for f in range(14):
    couche_low[f]  = np.trapz(inlayer[:,f]*spectre_low[:])
    couche_high1[f] = np.trapz(inlayer[:,f]*spectre_high1[:])
    couche_high2[f] = np.trapz(inlayer[:,f]*spectre_high2[:])
    couche[f]      = np.trapz(inlayer[:,f]*spectre[:])
    
ax.plot(np.linspace(1,14,14), couche/couche[11], '-r', label='Sim. low+highs')
ax.plot(np.linspace(1,14,14), couche_low/couche[11],  '--b', label='Sim. low')
ax.plot(np.linspace(1,14,14), couche_high1/couche[11], ':c', label='Sim. high1')
ax.plot(np.linspace(1,14,14), couche_high2/couche[11], ':m', label='Sim. high2')

# ax.set_yscale('log')

ax.set_xlim([0,15])
ax.set_xticks([0,2,4,6,8,10,12,14])
ax.set_ylim([0,5])
ax.grid(linestyle='--',alpha=0.5)
ax.set_xlabel('No. of RCF')
ax.set_ylabel('Normalized dose')
ax.legend(fancybox=False, reverse=True, frameon=False)
fig.set_size_inches(width, height)
fig.tight_layout()

fig.savefig('/Users/yao/Desktop/Spec1.pdf',dpi=600)

fig, ax = plt.subplots()
fig.subplots_adjust(left=.15, bottom=.16, right=.99, top=.97)

ax.plot(e_inc, spectre, '-r', label='Spectrum low+highs')
ax.plot(e_inc, spectre_low,  '--b', label='Spectrum low')
ax.plot(e_inc, spectre_high1, ':c', label='Spectrum high1')
ax.plot(e_inc, spectre_high2, ':m', label='Spectrum high2')
ax.set_yscale('log')

ax.set_xlim([0,45])
ax.set_ylim([1e-5,1e2])
ax.grid(linestyle='--',alpha=0.5)
ax.set_xlabel('Energy (MeV)')
ax.set_ylabel('dN/dE')
ax.legend(fancybox=False, reverse=True, frameon=False)
fig.set_size_inches(width, height)
fig.tight_layout()
fig.savefig('/Users/yao/Desktop/Spec2.pdf',dpi=600)



# plt.show()

In [14]:
fig, ax = plt.subplots()
fig.subplots_adjust(left=.15, bottom=.16, right=.99, top=.97)

yerr0=[np.abs(np.minimum(ave[:,0]-ms1[:,0], ave[:,0]-ms2[:,0], ave[:,0]-ms3[:,0])),
       np.maximum(ave[:,0]-ms1[:,0], ave[:,0]-ms2[:,0], ave[:,0]-ms3[:,0])
      ]

ax.errorbar(np.linspace(1,14,14),
            ave[:,0],
            yerr=yerr0, 
            fmt='-k',markersize=8,
            mfc='none',
            ecolor='k',elinewidth=2.0,
            capsize=2.0, capthick = 2.0,
            label='Exp.'
           )

ax.plot(np.linspace(1,14,14), 500*couche, '-r', label='Sim.')



ax.set_xlim([0,15])
ax.set_xticks([0,2,4,6,8,10,12,14])
ax.set_ylim([0,3000])
ax.grid(linestyle='--',alpha=0.5)
ax.set_xlabel('No. of RCF')
ax.set_ylabel('Dose (Gy)')
ax.legend(fancybox=False, reverse=True, frameon=False)
fig.set_size_inches(width, height)
fig.tight_layout()

fig.savefig('/Users/yao/Desktop/Dose.pdf',dpi=600)

In [28]:
width  = 3.487 * 1.5
height = width / 1.618 

fig, ax = plt.subplots()
fig.subplots_adjust(left=.15, bottom=.16, right=.99, top=.97)

# experiment
ax.errorbar(np.linspace(1,14,14),
            ave[:,0],
            yerr=yerr0, 
            fmt='-k',markersize=8,
            mfc='none',
            ecolor='k',elinewidth=2.0,
            capsize=2.0, capthick = 2.0,
            label='Exp.'
           )

factor = 500

e_inc = np.linspace(1,45,450)
spectre = np.zeros_like(e_inc)
spectre_low  = np.zeros_like(e_inc)
spectre_high1 = np.zeros_like(e_inc)
spectre_high2 = np.zeros_like(e_inc)
for p in range (e_inc.size):
    spectre_low[p] = 20*np.exp(-1.*np.sqrt(2*e_inc[p]/0.5))*factor
    # if e_inc[p] > 20:
    spectre_high1[p] = 0.1*np.exp(-0.5*((e_inc[p]-27.)/3.5)**4)*factor
    # else:
    spectre_high2[p] = 0.03*np.exp(-0.5*((e_inc[p]-22.)/5)**4)*factor
    spectre[p] =  spectre_low[p] + spectre_high1[p] + spectre_high2[p]

couche_low  = np.zeros_like(np.linspace(1,14,14))
couche_high1 = np.zeros_like(np.linspace(1,14,14))
couche_high2 = np.zeros_like(np.linspace(1,14,14))
couche      = np.zeros_like(np.linspace(1,14,14))

for f in range(14):
    couche_low[f]  = np.trapz(inlayer[:,f]*spectre_low[:])
    couche_high1[f] = np.trapz(inlayer[:,f]*spectre_high1[:])
    couche_high2[f] = np.trapz(inlayer[:,f]*spectre_high2[:])
    couche[f]      = np.trapz(inlayer[:,f]*spectre[:])
    
ax.plot(np.linspace(1,14,14), couche, '-r', label='Sim. low+high')
ax.plot(np.linspace(1,14,14), couche_low,  '--b', label='Sim. low')
ax.plot(np.linspace(1,14,14), couche_high1, ':c', label='Sim. high1')
ax.plot(np.linspace(1,14,14), couche_high2, ':m', label='Sim. high2')

# ax.set_yscale('log')

ax.set_xlim([0,15])
ax.set_xticks([0,2,4,6,8,10,12,14])
ax.set_ylim([0,3000])
ax.grid(linestyle='--',alpha=0.5)
ax.set_xlabel('No. of RCF')
ax.set_ylabel('Dose (Gy)')
ax.legend(fancybox=False, reverse=True, frameon=False)
fig.set_size_inches(width, height)
fig.tight_layout()

fig.savefig('/Users/yao/Desktop/Dose2.pdf',dpi=600)

fig, ax = plt.subplots()
fig.subplots_adjust(left=.15, bottom=.16, right=.99, top=.97)

factor2 = 2.0e10 / 32 / factor * 20

ax.plot(e_inc, spectre*factor2, '-r', label='low+high')
ax.plot(e_inc, spectre_low*factor2,  '--b', label='low')
ax.plot(e_inc, spectre_high1*factor2, ':c', label='high1')
ax.plot(e_inc, spectre_high2*factor2, ':m', label='high2')
ax.set_yscale('log')

ax.set_xlim([0,45])
ax.set_ylim([1e4,1e10])
ax.grid(linestyle='--',alpha=0.5)
ax.set_xlabel('Energy (MeV)')
ax.set_ylabel(r'dN/dE/d$\Omega$ (Part./MeV/sr)')
ax.legend(fancybox=False, reverse=True, frameon=False)
fig.set_size_inches(width, height)
fig.tight_layout()

fig.savefig('/Users/yao/Desktop/Spec_fixed.pdf',dpi=600)

# plt.show()

In [36]:
width  = 3.487 * 1.2
height = width / 1.618 

fig, ax = plt.subplots()
fig.subplots_adjust(left=.15, bottom=.16, right=.99, top=.97)

factor2 = 2.0e10 / 32 / factor * 20

ax.plot(e_inc, spectre*factor2, '-r', label='low+high')
# ax.plot(e_inc, spectre_low*factor2,  '--b', label='low')
# ax.plot(e_inc, spectre_high1*factor2, ':c', label='high1')
# ax.plot(e_inc, spectre_high2*factor2, ':m', label='high2')
ax.set_yscale('log')

ax.set_xlim([0,40])
ax.set_ylim([1e5,1e11])
ax.grid(linestyle='--',alpha=0.5)
ax.set_xlabel('Energy (MeV)',fontsize=13)
ax.set_ylabel(r'dN/dE/d$\Omega$ (Part./MeV/sr)',fontsize=13)
# ax.legend(fancybox=False, reverse=True, frameon=False)
fig.set_size_inches(width, height)
fig.tight_layout()

fig.savefig('/Users/yao/Desktop/Spec_fixed.pdf',dpi=600)

In [14]:
# calculate the deposited energy in each layer from the dose

surf_indiv = 7.168444444444446e-05                    # d'un pixel carre en cm^2       cm^2/px^2
energy = ave*1.2e-3*surf_indiv*28e-4
doseAvg = energy / ((str/29.6)*1.2e-3* 28e-4)

In [144]:
inlayer.shape

(450, 20)

In [90]:
plt.errorbar(np.linspace(1,14,14), 
             ave[:,0]/ave[0,0], 
             yerr=[
                 np.abs(np.minimum(ave[:,0]-ms1[:,0], ave[:,0]-ms2[:,0], ave[:,0]-ms3[:,0]))/ave[0,0],
                 np.maximum(ave[:,0]-ms1[:,0], ave[:,0]-ms2[:,0], ave[:,0]-ms3[:,0])/ave[0,0]
             ],
             
            )

<ErrorbarContainer object of 3 artists>

In [74]:
low  = np.minimum(ms1, ms2, ms3)

In [85]:
np.minimum(ave[:,0]-ms1[:,0], ave[:,0]-ms2[:,0], ave[:,0]-ms3[:,0])

array([-186.23744515,  -77.365929  , -114.73655506,  -42.2234008 ,
        -23.50512548, -138.60547616,  -71.09474857,  -27.63012019,
        -87.9669561 ,  -75.82240763, -130.98869403, -181.63762359,
        -65.95378782,  -25.39352261])

In [86]:
np.maximum(ave[:,0]-ms1[:,0], ave[:,0]-ms2[:,0], ave[:,0]-ms3[:,0])

array([369.60180877,  92.33607411,  16.61178473,  49.72990619,
        32.34563251, 282.56277812, 259.65144513,  10.72448624,
        72.22100005, 105.37962636,  80.77528031, 159.89465705,
        32.31268567,  45.42755249])

In [128]:
str/29.6

array([[0.00169805],
       [0.00166092],
       [0.00162501],
       [0.00157801],
       [0.00153302],
       [0.00148993],
       [0.00143799],
       [0.00138872],
       [0.00134194],
       [0.00129748],
       [0.0012552 ],
       [0.00120678],
       [0.0011611 ],
       [0.00111797]])

In [129]:
ave

array([[2394.28463259],
       [ 984.2862809 ],
       [ 454.72419868],
       [ 431.72447414],
       [ 653.94814051],
       [ 736.69173443],
       [ 727.3221996 ],
       [ 839.72821632],
       [ 837.22632113],
       [ 605.51620901],
       [ 660.8480854 ],
       [ 512.43371426],
       [ 538.98209985],
       [ 370.16078141]])