In [1]:
from turtle import pos

import matplotlib

matplotlib.use("MacOSX")  # for mac users

# print(matplotlib.get_backend())

import sys

import matplotlib as mpl

sys.path.append("/Users/yao/Smilei")
import happi
import matplotlib.pyplot as plt
import numpy as np

jetcmap = plt.cm.get_cmap(
    "jet", 9
)  # generate a jet map with 10 values "rainbow", "jet", YlOrRd
jet_vals = jetcmap(np.arange(9))  # extract those values as an array
jet_vals[0] = [1.0, 1, 1.0, 1]  # change the first value
jet_vals[8] = [0.0, 0, 0.0, 1]  # change the first value
newcmap = mpl.colors.LinearSegmentedColormap.from_list("mine", jet_vals)

from matplotlib import font_manager

font_dirs = ["/Users/yao/Documents/Calibri and Cambria Fonts/"]
font_files = font_manager.findSystemFonts(fontpaths=font_dirs)

for font_file in font_files:
    font_manager.fontManager.addfont(font_file)

# set font
plt.rcParams["font.family"] = "Calibri"

plt.rc("text", usetex=False)
plt.rc("xtick", labelsize=14)
plt.rc("ytick", labelsize=14)
plt.rc("axes", labelsize=14)
plt.rc("legend", fontsize=12)

import scienceplots as splt

plt.style.use(["nature", "notebook", "grid", "high-vis"])

/var/folders/2t/97rc3fl92tg15k2l_4sk5hsh0000gn/T/ipykernel_12130/4159834250.py:18: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap(obj)`` instead.
  jetcmap = plt.cm.get_cmap(


In [30]:
wkdir = [
    "/Users/yao/Documents/Data/IFE/ife_scaling_001-004/ife_004_a0300_ne120_res80_ppc4/",    
    "/Users/yao/Documents/Data/IFE/ife_scaling_001-004/ife_003_a0400_ne120_res80_ppc4/",    
    "/Users/yao/Documents/Data/IFE/ife_scaling_001-004/ife_001_a0500_ne120_res80_ppc4/",
    "/Users/yao/Documents/Data/IFE/ife_scaling_001-004/ife_002_a0600_ne120_res80_ppc4/",
    "/Users/yao/Documents/Data/IFE/ife_005_a0700_ne120_res80_ppc4/",
    "/Users/yao/Documents/Data/IFE/ife_006_a0800_ne120_res80_ppc4/",
    "/Users/yao/Documents/Data/IFE/ife_007_a0900_ne120_res80_ppc4/",
    ]

In [31]:
S0 = happi.Open(
    wkdir[0], reference_angular_frequency_SI=2.0 * np.pi * 3e8 / (1.0 * 1e-6)
)
S1 = happi.Open(
    wkdir[1], reference_angular_frequency_SI=2.0 * np.pi * 3e8 / (1.0 * 1e-6)
)
S2 = happi.Open(
    wkdir[2], reference_angular_frequency_SI=2.0 * np.pi * 3e8 / (1.0 * 1e-6)
)
S3 = happi.Open(
    wkdir[3], reference_angular_frequency_SI=2.0 * np.pi * 3e8 / (1.0 * 1e-6)
)
S4 = happi.Open(
    wkdir[4], reference_angular_frequency_SI=2.0 * np.pi * 3e8 / (1.0 * 1e-6)
)
S5 = happi.Open(
    wkdir[5], reference_angular_frequency_SI=2.0 * np.pi * 3e8 / (1.0 * 1e-6)
)
S6 = happi.Open(
    wkdir[6], reference_angular_frequency_SI=2.0 * np.pi * 3e8 / (1.0 * 1e-6)
)


Loaded simulation '/Users/yao/Documents/Data/IFE/ife_scaling_001-004/ife_004_a0300_ne120_res80_ppc4/'
Scanning for Scalar diagnostics
Scanning for Field diagnostics
Scanning for Probe diagnostics
Scanning for ParticleBinning diagnostics
Scanning for RadiationSpectrum diagnostics
Scanning for Performance diagnostics
Scanning for Screen diagnostics
Scanning for Tracked particle diagnostics
Scanning for new particle diagnostics
Loaded simulation '/Users/yao/Documents/Data/IFE/ife_scaling_001-004/ife_003_a0400_ne120_res80_ppc4/'
Scanning for Scalar diagnostics
Scanning for Field diagnostics
Scanning for Probe diagnostics
Scanning for ParticleBinning diagnostics
Scanning for RadiationSpectrum diagnostics
Scanning for Performance diagnostics
Scanning for Screen diagnostics
Scanning for Tracked particle diagnostics
Scanning for new particle diagnostics
Loaded simulation '/Users/yao/Documents/Data/IFE/ife_scaling_001-004/ife_001_a0500_ne120_res80_ppc4/'
Scanning for Scalar diagnostics
Scanning

In [4]:
Ey = np.array(S0.Probe(0,'Ey',units=["um", "fs"]).getData())
Ey.shape

(14, 1000, 1220)

In [ ]:
ne = np.array(S0.ParticleBinning(3,units=["um", "fs"]).getData())
ne.shape

(66, 1000, 1220, 3)

In [23]:
ne[:,:,:,1]

array([[[ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]],

       [[ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  

In [7]:
Ey_times = np.array(S0.Probe(0,'Ey',units=["um", "fs"]).getTimes())
ne_times = np.array(S0.ParticleBinning(3,units=["um", "fs"]).getTimes())

In [14]:
Ey_times

array([  0.        ,  16.66016371,  33.32032741,  49.98049112,
        66.64065482,  83.30081853,  99.96098223, 116.62114594,
       133.28130964, 149.94147335, 166.60163705, 183.26180076,
       199.92196446, 216.58212817])

In [9]:
ne_times

array([  0.        ,   3.31374998,   6.62749997,   9.94124995,
        13.25499993,  16.56874991,  19.8824999 ,  23.19624988,
        26.50999986,  29.82374984,  33.13749983,  36.45124981,
        39.76499979,  43.07874977,  46.39249976,  49.70624974,
        53.01999972,  56.3337497 ,  59.64749969,  62.96124967,
        66.27499965,  69.58874963,  72.90249962,  76.2162496 ,
        79.52999958,  82.84374956,  86.15749955,  89.47124953,
        92.78499951,  96.09874949,  99.41249948, 102.72624946,
       106.03999944, 109.35374942, 112.66749941, 115.98124939,
       119.29499937, 122.60874935, 125.92249934, 129.23624932,
       132.5499993 , 135.86374928, 139.17749927, 142.49124925,
       145.80499923, 149.11874921, 152.4324992 , 155.74624918,
       159.05999916, 162.37374914, 165.68749913, 169.00124911,
       172.31499909, 175.62874907, 178.94249906, 182.25624904,
       185.56999902, 188.883749  , 192.19749899, 195.51124897,
       198.82499895, 202.13874893, 205.45249892, 208.76

In [ ]:
for i in range(Ey_times.shape[0]):
    j = i*5
    

0.0 0.0
16.660163705303134 16.568749912681444
33.32032741060627 33.13749982536289
49.9804911159094 49.70624973804433
66.64065482121254 66.27499965072577
83.30081852651567 82.84374956340721
99.9609822318188 99.41249947608866
116.62114593712194 115.9812493887701
133.28130964242507 132.54999930145155
149.9414733477282 149.11874921413298
166.60163705303134 165.68749912681443
183.26180075833446 182.25624903949588
199.9219644636376 198.8249989521773
216.58212816894073 215.39374886485876


In [32]:
def get_S_para_t(S, label=None):
    Ey = np.array(S.Probe(0,'Ey',units=["um", "fs"]).getData())
    S_para_t = np.zeros(Ey.shape[0])
    for i in range(Ey.shape[0]):
        j=i*5
        Ey = np.array(S.Probe(0,'Ey',units=["um", "fs"
                                            # , "V/m"
                                            ]).getData()[i])
        ne = np.array(S.ParticleBinning(3,units=["um", "fs"
                                                    # , 'C m^{-3}'
                                                    ]).getData()[j])
        # S_para_t[i] = np.sum(rho_e/nr/qe * (-1.0) * np.abs(Ey/Er)**2) / lmd
        S_para_t[i] = np.sum(ne[:,610,1] * np.abs(Ey[:,610])**2)

    time = np.array(S.Probe(0,'Ey',units=["um", "fs"]).getTimes())
    return time, S_para_t, label

In [33]:
time0, S_para_t0, label0 = get_S_para_t(S0, 'a0=212')
time1, S_para_t1, label1 = get_S_para_t(S1, 'a0=282')
time2, S_para_t2, label2 = get_S_para_t(S2, 'a0=353')
time3, S_para_t3, label3 = get_S_para_t(S3, 'a0=424')
time4, S_para_t4, label4 = get_S_para_t(S4, 'a0=494')
time5, S_para_t5, label5 = get_S_para_t(S5, 'a0=565')
time6, S_para_t6, label6 = get_S_para_t(S6, 'a0=636')

In [37]:
# plt.plot(time0, S_para_t0, label=label0)
plt.plot(time1, S_para_t1, label=label1)
plt.plot(time2, S_para_t2, label=label2)
plt.plot(time3, S_para_t3, label=label3)
plt.plot(time4, S_para_t4, label=label4)
plt.plot(time5, S_para_t5, label=label5)
plt.plot(time6, S_para_t6, label=label6)

plt.xlabel("time (fs)")
plt.ylabel("S_para (NOT normalized)")
plt.legend()
plt.xlim([0, 120])
plt.ylim([0, 2e9])
# plt.title(r"$S=n_c^{-1} \lambda_L^{-1} \int_0^{L_x} dx n_e |a_0|^2$")
plt.title(r"$S=\int_0^{L_x} dx n_e |E_y|^2$")

plt.savefig("/Users/yao/Desktop/S_para_t_3D.png", dpi=300)